version: "3.9"
services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install; yarn run dev"
    ports:
      - 3004:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: todo-app
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo-app
volumes:
  todo-mysql-data:

